# Number of replicas of the web hook to be run. We suggest a minimum of 2 for fault tolerance
replicaCount: 2

# This needs to be the CA Root of your cluster encoded in base64
# you can get this by running the following command
# kubectl get configmap -n kube-system extension-apiserver-authentication -o=jsonpath='{.data.client-ca-file}' | base64 | tr -d '\n'
caBundle: 

# This is the url of the registry that you wish your cluster.local images to be pulled from.
# If you specified scott.com it woudl re-write cluster.local/some/image to scott.com/some/image
containerRegistryUrl: 

# The name of the image pull secret to be used for the repository
imagePullSecretName: 

webhookImage: mgkaiser/mutatingcontroller:0.1.0